### ISSUE TITLE
3.3.4.1	SAULĖ IS informacijos viešinimas

### ISSUE THREAD

**Issue by RMasiliunaite** [Viesuju-pirkimu-tarnyba/saule#31]
Proceso trumpas aprašymas: 

Procesas skirtas SAULĖ IS saugomų duomenų viešinimo veiklų automatizavimui. Procesas užtikrina galimybę Sistemos administratoriui:
•	Nustatyti automatines duomenų ar jų grupių viešinimo/neviešinimo taisykles;
•	Nustatyti automatiškai viešinamų duomenų pateikimo formatą, vietą, dažnumą ir kt. taisykles;
•	Nustatyti automatiškai viešinamų duomenų panaikinimo (neviešinimo) terminą;
•	Nustatyti SAULĖ IS naudotojų analizės parametrus (Google analitika ar lygiavertės programinės įrangos pagalba), rodiklius ar kitą naudotojų žingsnių analitinę analizę.

Kokiais atvejais procesas inicijuojamas – esant poreikiui viešinti SAULĖ IS duomenis. 

3.19 lentelė. Proceso dalyviai

Dalyviai | Dalyvio vaidmuo, veiksmai ir funkcijos
-- | --
Sistemos administratorius | Dalyvis atlieka šiuos veiksmus:    ¨         Nustato automatines SAULĖ IS duomenų ar jų   grupių viešinimo/neviešinimo taisykles;   ¨         Nustato automatiškai viešinamų duomenų   pateikimo formatą, vietą, dažnumą ir kt. taisykles;   ¨         Nustato automatiškai viešinamų duomenų   panaikinimo (neviešinimo) terminą.
SAULĖ IS | Sistema, kurioje atliekami   veiksmai
Kitų organizacijų IS | Sistemos, kurios per   integracinę sąsają (API, XML formatu) gauna SAULĖ IS viešinamus duomenis

Procese aprašomas šių rezultatų pasiekimas:
•	Informacijos viešinimas. 

Procesas „SAULĖ IS informacijos viešinimas“ yra susijęs su visais SAULĖ IS procesais.

Proceso įeitis (angl. input) | Proceso rezultatas   (angl. output) | Lydintys ar įtakojantys   dokumentai
-- | -- | --
SAULĖ IS kaupiami duomenys | Išviešinta reikiama informacija ir duomenys | -

![image](https://user-images.githubusercontent.com/61745726/81939895-99567280-95ff-11ea-9cd9-a6df28ab5b2d.png) 3.8 pav. Proceso „SAULĖ IS informacijos viešinimas“ diagrama

3.21 lentelė. Proceso SAULĖ IS informacijos viešinimas“ aprašymas

Žingsnio Nr. | Žingsnio pavadinimas | Proceso dalyvis | Aprašymas | Taikomi reikalavimai | Teisinis    reglamen-tavimas
-- | -- | -- | -- | -- | --
E1 | Poreikis viešinti informaciją | Sistemos administratorius | Iškilo poreikis viešinti informaciją. |   |  
T1 | Pasirinkti duomenis / duomenų paketą | Sistemos administratorius | Sistemos administratorius pasirenka pavienius   duomenis arba duomenų paketus, kuriuos nori viešinti. | Turi būti galima pasirinkti pavienius duomenis.   Turi būti galima pasirinkti duomenų paketus. |  
T2 | Nustatyti viešinimo parametrus | Sistemos administratorius | Sistemos   administratorius pasirenka viešinimo formatą. | Turi būti galimybė pasirinkti viešinimo formatą. |  
T3 | Pasirinkti viešinimo kanalą (-us) | Sistemos administratorius | Sistemos administratorius pasirenka viešinimo kanalą   (Facbeook, twitter, el. paštas, kitos informacinės sistemos (web   service priemonėmis) ir kt.) ir duomenų pateikimo formatą. | Turi būti galimybė pasirinkti viešinimo kanalą. |  
T4 | Nustatyti viešinimo periodiškumą | Sistemos administratorius | Sistemos administratorius   nustato viešinimo periodiškumą (data nuo iki). | Turi būti galimybė nustatyti viešinimo periodiškumą. |  
T5 | Nustatyti viešinimo algoritmą | Sistemos administratorius | Sistemos administratorius nustato viešinimo algoritmą   (Pvz.: Informacijos paketas apie statybas bus viešinamas, jei įrašyta   medžiaga „medis“ ir visi susiję pirkimai.). | Turi būti galimybė nustatyti viešinimo algoritmą. |  
T6 | Išsaugoti nustatyti parametrus | Sistemos administratorius | Sistemos administratorius inicijuoja parametrų   išsaugojimo veiksmą. | Sistemos administratoriui inicijavus veiksmą saugoti   parametrus turi išsaugoti nustatytus parametrus. |  
E2 | Proceso pabaiga | Sistemos administratorius | - | - |

**Comment by sirex** [comment]
Čia eina kalba apie atvirus duomenis? Ar kažką kita?

**Comment by RMasiliunaite** [comment]
> Čia eina kalba apie atvirus duomenis? Ar kažką kita?

Čia kalbama apie duomenis, kurie yra vieši, t.y. viešai skelbiamos ataskaitos, skelbimai, kiti duomenys. Jie paskui gali tapti atvirais duomenimis.
