### ISSUE TITLE
3.3.12.3	VPT konsultacijos gyvai 

### ISSUE THREAD

**Issue by RMasiliunaite** [Viesuju-pirkimu-tarnyba/saule#65]
Dalyviai | Dalyvio vaidmuo
-- | --
Pagalbos   posistemės specialistas | Dalyvis atlieka šiuos veiksmus:      ¨         gavus paklausimą inicijuoja problemos   sprendimą ar pašalinimą;   ¨         gyvai atsako SAULĖ IS naudotojui;   ¨         esant poreikiui, inicijuoja sistemos defekto   pašalinimo užsakymą iš išorinių paslaugų teikėjų (formuojamas užsakymas);   ¨         pašalinto sistemos defekto testavimas ir   uždarymas;   ¨         uždaro fiksuotą problemą.
Paslaugų teikėjai | Dalyvis atlieka šiuos veiksmus:      ¨         Gavus užsakymą, defekto pašalinimas ir   derinimas su  pagalbos posistemės   specialistu arba pateikiamas alternatyvus siūlymas gautos problemos   sprendimui;   ¨         Gavus patvirtinimą, atnaujintos programinės   įrangos diegimas.
Naudotojai | Dalyvis atlieka šiuos veiksmus:      ¨         inicijuoja problemą pateikdami paklausimą,   fiksuodami defektą pagalbos tarnybos priemonėmis;   ¨         esant poreikiui, teikia informaciją;   ¨         uždaro fiksuotą problemą.
SAULĖ IS | Sistema, kurioje atliekami veiksmai

![image](https://user-images.githubusercontent.com/61745726/82138370-94283c00-9828-11ea-85c0-7b8586150161.png) 3.39 pav. Proceso „VPT Konsultacija gyvai“ diagrama

3.114 lentelė. Proceso „VPT konsultacijos gyvai“ aprašymas

Žingsnio Nr. | Žingsnio pavadinimas | Proceso dalyvis | Aprašymas | Taikomi reikalavimai | Teisinis    reglamen-tavimas
-- | -- | -- | -- | -- | --
E1 | Poreikis pateikti paklausimą gyvai | Naudotojas | - | - | -
T1 | Inicijuoti pokalbį | Naudotojas | Inicijuojamas pokalbis gyvai. | Turi būti galimybė pasirinkti konsultaciją gyvai. | -
T2 | Pateikti paklausimą | Naudotojas | Pateikiamas klausimas, pagal pasirinktą temą. | Iš išskleidžiamo sąrašo turi būti galimybė pasirinkti   temą.   Turi būti galimybė parašyti klausimą.   Turi būti galimybė bendrauti realiu laiku. | -
T3 | Priskirti pagalbos posistemės specialistą | Pagalbos tarnybos PĮ | Priskiriamas pagalbos posistemės specialistas pagal   pasirinktą temą. | Automatiniu būdu turi būti priskiriamas specialistas   pagal pasirinktą temą. | -
T4 | Pateikti atsakymus | Pagalbos posistemės specialistas | Pateikiamas atsakymas į užduotą (-us) klausimą (-us). | Priskirtam asmeniui turi būti galimybė priskirti   užduotį kitam asmeniui.   Turi būti galimybė bendrauti realiu metu. |  
T5 | Užregistruoti defektą | Pagalbos posistemės specialistas | Jei pranešamas defektas užregistruojamas defektas   klaidų registravimo programinėje įrangoje. | Turi būti galimybė užregistruoti defektą klaidų   registravimo PĮ. |  
T6 | Pašalinti defektą | Pagalbos posistemės specialistas | Jei defektą įmanomą pašalinti   - pašalinamas defektas.   Jei defekto neįmanoma pašalinti nusprendžiamas   žingsnių siūlymas, kaip defektą būtų galima apeiti. | - |  
T7 | Užbaigti pokalbį | Naudotojas / Pagalbos posistemės specialistas | Jei atsakyti klausimai ir nereikalingas defekto   registravimas užbaigiamas pokalbis.   Jei reikia užregistruoti defektą, užregistruojamas   defektas ir informuojamas naudotojas per kiek laiko defektas bus pašalinamas   ir užbaigiamas pokalbis. | Turi būti galimybė užbaigti pokalbį. |  
E2 | Proceso pabaiga | - | - | - |

**Comment by sirex** [comment]
Gal konsultacijas gyvai reikėtų pakeisti chatbotais? T.y. pirmiausiai pagalba bandytų suteikti chatbotas, tačiau jei chatbotas nesusitvarko, tada perleistų pokalbį gyvam konsultantui.

Chatbotas būtų labai veiksmingas, jei užklausos yra pasikartojančios.

Chatbotas gali ne tik atsakyti į klausimus, bet ir realiai pašalinti defektus.
