### ISSUE TITLE
3.3.1	Duomenų srautų schema

### ISSUE THREAD

**Issue by RMasiliunaite** [Viesuju-pirkimu-tarnyba/saule#91]
![image](https://user-images.githubusercontent.com/61745726/81700592-87df6000-9471-11ea-8453-b77338a2d8e1.png)6 pav. Saulė IS duomenų srautų schema

Žemiau pateikta išorinių duomenų teikėjų planuojamų teikti per integracijų platformą duomenų aprašymas (turi būti tikslinama po susitikimų su institucijomis, su kuriomis numatytos integracinės sąsajos).

12 lentelė. Saulė IS duomenų teikėjų teikiamų duomenų aprašymas

Nr. | Duomenis teikianti IS | Duomenų aprašymas[1]
-- | -- | --
1. | JAR (RC) | Duomenys apie SAULĖ IS   registruotus juridinius asmenis:    ·         objekto kodas (9 skaitmenų);    ·         kodas prieš Juridinių asmenų registro steigimą (7 skaitmenų);   ·         aktualus objekto pavadinimas;    ·         teisinės formos kodas;    ·         teisinio statuso kodas;    ·         juridinio asmens veiklos apribojimai:    ·         apribota juridinio asmens veikla, duomenys apie instituciją, priėmusią   sprendimą dėl juridinio asmens veiklos apribojimo ar apribojimo panaikinimo,   ir sprendimo priėmimo (įsiteisėjimo) data;    ·         objekto įregistravimo data;    ·         objekto steigimo data (tradicinėms religinėms bendruomenėms ir   profsąjungoms);    ·         išregistravimo data;    ·         buveinės adresas (tekstu bei adreso elementais pagal Adresų registro   klasifikaciją – administracinio vieneto, gyvenamosios vietovės, gatvės   identifikatoriai, namo, patalpos ar buvo numeris);   ·         filialo, atstovybės steigimo duomenys (pavadinimas, kodas);   ·         vadovo vardas, pavardė, pareigų pavadinimas;    ·         objekto kontaktiniai duomenys (telefonas, faksas, el. pašto adresas,   interneto svetainės adresas);    ·         registro tvarkytojo pavadinimas, registro versijos numeris ir data;
2. | IS „E. sąskaita“ (RC) | Sąskaitų faktūrų duomenys:    ·         kreditinio ir debetinio dokumento bei avansinės sąskaitos serija ir   numeris;    ·         PVM sąskaitos-faktūros, kreditinio ir debetinio dokumento bei   avansinės sąskaitos išrašymo data;    ·         pardavėjas (pardavėjo juridinio asmens kodas, pardavėjo pavadinimas,   pardavėjo adresas, PVM mokėtojo kodas);   ·         pirkėjas (pirkėjo juridinio asmens kodas, pirkėjo pavadinimas, pirkėjo   adresas, PVM mokėtojo kodas);    ·         sutarties numeris;    ·         sutarties identifikatorius;    ·         prekės ar paslaugos (pavadinimas, kiekis, tiekiamos prekės arba   teikiamos paslaugos vieneto kaina (be PVM), PVM tarifas (tarifai) ir kodas   (kodai), PVM suma), suma;    ·         valiuta;   ·         viešojo pirkimo numeris.
3. | SFMIS (FM) | Iš 2007-2013 metų Europos   sąjungos struktūrinės paramos posistemio gaunami duomenys:    ·         SFMIS naudotojo vardas;   ·         Naudotojo pašalinimo data;   ·         Naudotojo būsena: aktyvus/blokuotas;   ·         Naudotojo vardas;   ·         Naudotojo pavardė;   ·         Institucijos, kuriai priklauso naudotojas, trumpinys;   ·         Institucijos, kuriai priklauso naudotojas, kodas;   ·         Naudotojui nurodytos pareigos;   ·         Naudotojo telefono numeris;   ·         Naudotojo el. paštas;   ·         Projekto kodas, kuriam naudotojas priskirtas kaip atsakingas   darbuotojas;   ·         Projekto pavadinimas, kuriam naudotojas priskirtas kaip atsakingas   darbuotojas;   ·         Projekto būsena (kokios reikšmės galimos?),   ·         Projekto įgyvendinimo pradžia;   ·         Projekto įgyvendinimo pabaiga;   ·         Įtarimo registravimo data,    ·         Įtarimo tyrimo būsena (0 – vyksta, 1 – baigtas),    ·         Įtarimo aprašymas,    ·         Ar nustatytas pažeidimas? (0 – ne, 1 – taip),    ·         Pažeidimo identifikacinis SFMIS kodas,    ·         Pažeidimo unikalus kodas,    ·         Pažeidimo nustatymo data,    ·         Pažeidimo tipo kodas (klasifikatorius sistemoje),    ·         Pažeidimo papildomas tipo kodas (klasifikatorius sistemoje).   ·         Pažeidimų tipų klasifikatoriaus duomenys:   ·         Kodas;   ·         pavadinimas       Iš 2014-2020 metų Europos   sąjungos struktūrinių fondų gaunami duomenys:    ·         SFMIS naudotojo vardas;   ·         Naudotojo pašalinimo data;   ·         Naudotojo būsena: aktyvus/blokuotas;   ·         Naudotojo vardas;   ·         Naudotojo pavardė;   ·         Institucijos, kuriai priklauso naudotojas, trumpinys;   ·         Institucijos, kuriai priklauso naudotojas, kodas;   ·         Naudotojui nurodytos pareigos;   ·         Naudotojo telefono numeris;   ·         Naudotojo el. paštas;   ·         Projekto kodas, kuriam naudotojas priskirtas kaip atsakingas   darbuotojas;   ·         Projekto pavadinimas, kuriam naudotojas priskirtas kaip atsakingas   darbuotojas;   ·         Projekto būsena (kokios reikšmės galimos?),   ·         Projekto įgyvendinimo pradžia;   ·         Projekto įgyvendinimo pabaiga;   ·         Įtarimo registravimo data,    ·         Įtarimo tyrimo būsena (0 – vyksta, 1 – baigtas),    ·         Įtarimo aprašymas,    ·         Ar nustatytas pažeidimas? (0 – ne, 1 – taip),    ·         Pažeidimo identifikacinis SFMIS kodas,    ·         Pažeidimo unikalus kodas,    ·         Pažeidimo nustatymo data,    ·         Pažeidimo tipo kodas (klasifikatorius sistemoje),    ·         Pažeidimo papildomas tipo kodas (klasifikatorius sistemoje).       Pažeidimų tipų klasifikatoriaus duomenys:   ·         Kodas;   ·         Pavadinimas.
4. | EDAS (VSDFV) | Duomenys apie SAULĖ IS   registruotus fizinius ir juridinius asmenis:    ·       Įmonės kodas arba asmens   kodas, kurio informacija yra tikrinama;   ·         Draudėjo kodas;   ·         Duomenų formavimo data;   ·         Duomenų formavimo laikas;   ·         Skolos Valstybinio socialinio draudimo fondo biudžetui dydis;   ·       Indikatorius ar yra   skola/permoka.
5. | ESKIS (VMI) | Duomenys apie SAULĖ IS   registruotus fizinius ir juridinius asmenis (iš ESKIS gauti informacija, ar   tiekėjas (juridinis (JA) arba fizinis asmuo (FA) turi permoką arba skolą VMI   (pagal užklausą pateikus JA/FA kodą):    ·       JA/FA kodas    ·         JA pavadinimas arba FA vardas ir pavardė;   ·         Duomenų formavimo data;   ·         Duomenų formavimo laikas;   ·         informacija, ar verslininkas turi permoką arba skolą VMI;   ·         Nuoroda į ManoVMI portalą (ESKIS) (kai reikia peržiūrėti skolos dydį   arba neformuoja duomenų automatiniu būdu. Nuoroda turi būti suformuota iš   karto su užklausos parametrais dėl konkretaus JA/FA).   ·         Duomenys apie Lietuvos ir užsienio juridinius asmenis (mokesčių   mokėtojus), nuolatinius ir nenuolatinius Lietuvos gyventojus, vykdančius   individualią veiklą, vykdančius veiklą pagal Verslo liudijimus, asmenis   vykdančius individualią žemės ūkio veiklą. Kartu norima gauti mokesčio   mokėtojo kodą, PVM kodą, tipą, veiklos rūšys, veiklos formą ir jos duomenis   (individualios veiklos pažymėjimo duomenis, verslo liudijimo duomenis ir pan.   (išdavimo data ir numeris).
6. | PIDTIS arba   PIR (VTEK). | Duomenys   apie SAULĖ IS registruotus fizinius asmenis:   ·       Fizinių asmenų deklaracijų tikrinimui   reikalingi duomenys:   ·         Privačių interesų deklaracijos duomenys:   ¨     asmens duomenys (vardas,   pavardė, asmens kodas);   ¨     pateikimo data;   ¨     darbovietės duomenys   (juridinio asmens kodas, pavadinimas, telefono nr., pareigos).
7. | ĮKNR (IRD) | Duomenys   apie fizinius asmenis, atstovaujančius SAULĖ IS registruotus naudotojus   (juridinių asmenų atstovus):   ·       asmens kodas (įrašomas,   jeigu jis suteiktas Lietuvos Respublikos gyventojų registro įstatymo   nustatyta tvarka);   ·         Europos Sąjungos valstybėje narėje fiziniam asmeniui priimto   apkaltinamojo teismo nuosprendžio duomenys:   ¨     apkaltinamojo nuosprendžio   priėmimo data;   ¨     apkaltinamojo nuosprendžio   įsiteisėjimo data.
8. | ANR (IRD) | Administracinį nusižengimą ar administracinį   teisės pažeidimą (toliau kartu – administracinis nusižengimas) padariusio   fizinio asmens duomenys:   ·         asmens kodas;   ·         administracinio nusižengimo duomenys:   ¨       administracinio nusižengimo padarymo data ir laikas;   ¨       administracinio nusižengimo esmė (trumpas administracinio nusižengimo   aprašymas) (jei iš ANK straipsnio negalima spręsti, ar nebuvo 46 str. 4 d. 7   p. minimų nuobaudų, tuomet reikalingas aprašymas);   ¨       Administracinių nusižengimų kodekso ar Administracinių teisės   pažeidimų kodekso straipsnis, dalis, punktas, kuriuose nustatyta   administracinė atsakomybė už padarytą administracinį nusižengimą, pažeidimo   sunkumo lygis;   ¨       kito teisės akto, už kurio pažeidimą asmuo traukiamas administracinėn   atsakomybėn, pavadinimas, straipsnis, dalis, punktas, papunktis;   ¨       informacija ir žyma, kad padaryta mažai pavojinga veika, nustatyta   Administracinių nusižengimų kodekso 12 straipsnyje „Mažai pavojinga veika“.
9. | VIISP (IVPK) | VIISP   teikiami asmens prisijungimo identifikavimo duomenys:   ·       vardas,    ·         pavardė,    ·         asmens kodas.
10. | GR (RC) | Iš   GR gaunami duomenys apie fizinio asmens statusą gyventojų registre pagal   pateiktą užklausą (asmens kodas, vardas pavardė).
11. | AVNIS (FM) | Audito, vertinimo ir nemokumo sistema AVNIS.       Duomenys apie fizinį asmenį, kuriam iškelta bankroto byla (pagal   pateiktą užklausą):   ·         vardas, pavardė;   ·         asmens kodas;   ·       duomenys apie fizinio   asmens bankroto proceso eigą (Sprendimo baigti bankroto bylą įsiteisėjimo   data).
12. | NORIS (FM) | Iš NORIS gaunami šie duomenys:   ·       SFMIS naudotojo vardas;   ·         Naudotojo pašalinimo data;   ·         Naudotojo būsena: aktyvus/blokuotas;   ·         Naudotojo vardas;   ·         Naudotojo pavardė;   ·         Institucijos, kuriai priklauso naudotojas, trumpinys;   ·         Institucijos, kuriai priklauso naudotojas, kodas;   ·         Naudotojui nurodytos pareigos;   ·         Naudotojo telefono numeris;   ·         Naudotojo el. paštas;   ·         Projekto kodas, kuriam naudotojas priskirtas kaip atsakingas   darbuotojas;   ·         Projekto pavadinimas, kuriam naudotojas priskirtas kaip atsakingas   darbuotojas;   ·         Projekto būsena (kokios reikšmės galimos?),   ·         Projekto įgyvendinimo pradžia;   ·         Projekto įgyvendinimo pabaiga;   ·         Įtarimo registravimo data,    ·         Įtarimo tyrimo būsena (0 – vyksta, 1 – baigtas),    ·         Įtarimo aprašymas,    ·         Ar nustatytas pažeidimas? (0 – ne, 1 – taip),    ·         Pažeidimo identifikacinis SFMIS kodas,    ·         Pažeidimo unikalus kodas,    ·         Pažeidimo nustatymo data,    ·         Pažeidimo tipo kodas (klasifikatorius sistemoje),    ·       Pažeidimo papildomas tipo   kodas (klasifikatorius sistemoje).   Pažeidimų tipų   klasifikatoriaus duomenys:   ·       Kodas;   ·       pavadinimas
13. | PAIIS (RC) | PAIIS perduos į SAULĖ IS šiuos duomenis, kurie turi būti suderinti   išsamios analizės ir projektavimo etape:    ·       ūkio subjekto duomenys (JA   kodas);   ·         veiklos patikrinimo duomenys;    ·         veiklos patikrinimą atlikusių priežiūros institucijos pavadinimas ir   priežiūrą atlikusio darbuotojo duomenys;    ·         duomenys apie veiklos patikrinimo metu nustatytus faktus;   ·         taikytų ekonominių sankcijų duomenys.
14. | CPO IS (CPO) | CPO vykdomų pirkimų ir sudarytų sutarčių duomenys.
15. | LITEKO (NTA) | LITEKO teikia duomenis apie su pirkimų vykdymu   susijusias bylas:   ·       Pirkimo numeris;   ·         Perkančiosios organizacijos pavadinimas;   ·         Perkančiosios organizacijos įmonės kodas;   ·         Pirkimo pavadinimas;   ·         Bylos numeris;   ·         Bylos statusas;   ·         Nuoroda į nuosprendžio tekstą.
16. | Standartų IS   (Standartizacijos departamentas) | Standartų pavadinimų sąrašo   gavimas. Galutinis poreikis bus patikslintas ir suderintas su   Standartizacijos departamentu integracijos derinimo metu.
17. | DAKPR (Švietimo agentūra) | Diplomų, atestatų ir kvalifikacijos pažymėjimų registras DAKPR.       Duomenys apie SAULĖ IS registruotų naudotojų pasiūlymuose   nurodytus fizinius asmenis:   ·       Registro objektai yra   mokymosi pasiekimus įteisinantys dokumentai:   ¨     pagrindinio išsilavinimo   įgijimą patvirtinantys pažymėjimai ir jų dublikatai;   ¨     vidurinio išsilavinimo   įgijimą patvirtinantys brandos atestatai ir jų dublikatai;   ¨     profesinio mokymo   kvalifikacijos pažymėjimai ir jų dublikatai;   ¨     profesinio mokymo diplomai   (kodai 4101, 4102) ir jų dublikatai;   ¨     profesinio mokymo diplomai   (kodai 3110, 3111) ir jų dublikatai;   ¨     aukštojo mokslo   kvalifikacijas patvirtinantys diplomai ir jų dublikatai.   ·         Registro duomenų bazėje apie visus Registro objektus kaupiami šie   bendrieji Registro objekto duomenys:   ¨     identifikavimo kodas;   ¨     dokumento pavadinimas;   ¨     asmens, kuriam išduotas   dokumentas, asmens kodas (jeigu asmens kodo nėra – gimimo data ir lytis);   ¨     institucijos, kurioje   įgytas išsilavinimas, juridinio asmens kodas;   ¨     institucijos, kurioje   įgytas išsilavinimas, pavadinimas;   ¨     institucijos (-ų),   išdavusios (-ių) dokumentą, juridinio asmens kodas;   ¨     institucijos (-ų),   išdavusios (-ių) dokumentą, pavadinimas;   ¨     dokumento išdavimo data;   ¨     baigtos švietimo programos   valstybinis kodas (išskyrus mokslo (meno) laipsnį patvirtinančius diplomus);   ¨     baigtos švietimo programos   pavadinimas (išskyrus mokslo (meno) laipsnį patvirtinančius diplomus);   ¨     įgytas išsilavinimas (jei   įgytas) ir kodas (jeigu yra);   ¨     suteikta kvalifikacija (jei   suteikta) ir kodas (jeigu yra).   ¨     apie profesinio mokymo   kvalifikacijos pažymėjimus:   ¨     kvalifikacijos įgijimo   metai;   ¨     profesinio standarto arba   profesinio rengimo standarto pavadinimas ir kodas, jo nesant – atitinkamos   formaliojo profesinio mokymo programos, įregistruotos Studijų, mokymo   programų ir kvalifikacijų registre, pavadinimas ir valstybinis kodas,   kuriuose aprašyta kvalifikacijos pažymėjime įvardyta kvalifikacija;   ¨     kvalifikacijos pažymėjime   įvardytos kvalifikacijos lygis pagal Lietuvos kvalifikacijų sandaros aprašą,   patvirtintą Lietuvos Respublikos Vyriausybės 2010 m. gegužės 4 d. nutarimu   Nr. 535 „Dėl Lietuvos kvalifikacijų sandaros aprašo patvirtinimo“, nurodytas   formaliojo profesinio mokymo programoje;   ¨     kvalifikacijos pažymėjime   įvardytos kvalifikacijos lygis pagal Europos mokymosi visą gyvenimą   kvalifikacijų sąrangą, nurodytas formaliojo profesinio mokymo programoje;   ¨     išduoto profesinio mokymo   kvalifikacijos pažymėjimo numeris Kvalifikacijos ir mokymosi pasiekimų   dokumentų apskaitos žurnale;   ·         apie profesinio mokymo diplomus (kodai 4101, 4102):   ¨       kvalifikacijos įgijimo metai.
18. | Išorinės   verslo IS (pirkimų vykdytojų) | Gauti į SAULĖS IS (planuojamų   integracijų sąrašas):   ·       Organizacijos metinio   viešųjų pirkimų plano duomenys (pateikiami pirmą kartą)/keitimo duomenys   ·         Pirkimų duomenys/pirkimų sąlygų duomenys   ·         Prašymas Viešųjų pirkimų tarnybai vykdyti pirkimą    ·         Kvietimų duomenys   ·         Rinkos konsultacijų duomenys   ·         Sutarties duomenys/keitimo/nutraukimo/ būsenų duomenys   ·         Sąskaitų duomenys   ·         Faktinė atlikto pirkimo vertė   ·         Pirkimų sutarties, kurie nebuvo per SAULĖ IS vykdomi, duomenys   ·         Tipinių ataskaitų duomenys   ·         Pirkimo per CPO duomenys, nepirkimo per CPO pagrindimai   ·         Neskaidymo į dalis pagrindimai   ·       Nereguliarių pirkimų   duomenys ir pagrindimai.

Žemiau pateiktas duomenų gavėjų sąrašas ir planuojamų jiems teikti duomenų iš SAULĖ IS per integracijų platformą aprašymas.

13 lentelė. Saulė IS duomenų gavėjų integracinių sąsajų aprašymas

Nr. | Duomenis gaunanti IS | Duomenų aprašymas[1]
-- | -- | --
1. | IS „E. sąskaita“(RC) | IS „E. sąskaita“   teikiami SAULE IS priemonėmis pasirašytų pirkimų sutarčių duomenys:   ·       Dokumento identifikacinis   numeris;   ·         BVPŽ kodas;   ·         Perkančiosios (-iųjų) organizacijos (-ų) įmonės (-ių) kodas (-ai);   ·         Tiekėjo (-ų) įmonės (-ių) kodas (-ai) arba asmens (-ų) kodas (-ai);   ·         Sutarties numeris;   ·         Sutarties sudarymo data;   ·       Sutarties galiojimo data.
2. | TED | TED teikiami duomenys apie pirkimą ir jo skelbimo   turinį pagal numatytą TED integracijų specifikaciją.    Šiuo metu jau realizuota sąsaja, esant galimybei, turi   būti perpanaudota. Pasikeitus integracijų specifikacijai ir duomenų apimčiai,   bus atnaujinta arba sukurta nauja integracinė sąsaja.
3. | ANR (IRD) | ANR   perduodami SAULE IS suformuoti pažeidimų protokolų duomenys apie   administracinį nusižengimą ar administracinį teisės pažeidimą padariusį   asmenį (FA/JA):   ·       juridinio asmens kodas;   ·         fizinio asmens kodas;   ·         administracinio nusižengimo duomenys:   ¨     administracinio nusižengimo   padarymo data ir laikas;   ¨     administracinio nusižengimo   esmė (trumpas administracinio nusižengimo aprašymas) (jei iš ANK straipsnio   negalima spręsti, ar nebuvo 46 str. 4 d. 7 p. minimų nuobaudų, tuomet   reikalingas aprašymas);   ¨     Administracinių nusižengimų   kodekso ar Administracinių teisės pažeidimų kodekso straipsnis, dalis,   punktas, kuriuose nustatyta administracinė atsakomybė už padarytą   administracinį nusižengimą, pažeidimo sunkumo lygis;   ¨     kito teisės akto, už kurio   pažeidimą asmuo traukiamas administracinėn atsakomybėn, pavadinimas, straipsnis,   dalis, punktas, papunktis;   ¨     informacija ir žyma, kad   padaryta mažai pavojinga veika, nustatyta Administracinių nusižengimų kodekso   12 straipsnyje „Mažai pavojinga veika“.
4. | PAIIS (RC) | PAIIS teikiami SAULE IS   duomenys (pagal PAIIS pateiktą integracijų specifikacijos reikalavimus):   ·         ūkio subjekto duomenys (JA kodas);   ·         ūkio subjektų patikrinimo plano duomenys:   ¨     tikrinamas ūkio subjektas   (JA pavadinimas, kodas, FA vardas (-ai), pavardė (-ės));   ¨       tikrinamo ūkio subjekto veiklos adresas;   ¨       veiklos patikrinimo terminas;   ¨       veiklos patikrinimo tikslas;   ¨       ūkio subjektų informavimo duomenys (FA telefono ryšio numeris,   elektroninio pašto adresas);   ¨       pavedimo atlikti veiklos patikrinimą duomenys;   ·         veiklos patikrinimo duomenys:   ¨       tikrinamas ūkio subjektas (JA pavadinimas, kodas, FA vardas (-ai),   pavardė (-ės));   ¨       veiklos patikrinimo tipas;   ¨       patikrinimo atlikimo vieta;   ·         veiklos patikrinimą atlikusių priežiūros institucijos darbuotojų   duomenys;   ·         duomenys apie veiklos patikrinimo metu nustatytus faktus;   ·         kontrolinio klausimyno duomenys.
5. | CPO IS (CPO) | Duomenis iš CPO IS planuojama gauti   pagal pateiktą SAULĖ IS užklausą (organizacijos JA kodas ir pirkimų Nr. (tų JA   pirkimų, kur pirkimo plane CPO nurodyta kaip pirkimo vykdytoja).       Planuojama iš CPO IS gauti   įvykdytų pirkimų duomenis (kartu grąžins duomenis su SAULE IS pirkimo Nr.   Kokia bus tiksli grąžinamų duomenų aibė ir kokių pirkimų būsenų duomenys bus   reikalingi bus patikslinti po susitikimų su CPO integracijų derinimo metu.
6. | Priežiūros institucijų IS | Duomenis perduoti sutartu   būdu.
7. | Išorinės verslo IS (pirkimų   vykdytojų) | Teikti iš SAULĖS IS   (universali sąsaja skirta visiems):   ·          BVPŽ kodų klasifikatorius   ·          Susirašinėjimų duomenys   ·          Pretenzijų duomenys   ·          Pasiūlymų duomenys   ·          Pasiūlymų/paraiškų vertinimo duomenys   ·          Laimėjusio pasiūlymo viešinimo duomenys   ·          Sutarties duomenys/keitimo/nutraukimo/ būsenų   duomenys   ·          Pirkimo būsenų duomenys   ·          Komisijos narių ir komisijos protokolų   duomenys   ·          VPT išvadų duomenys   ·          Melagingą informaciją pateikusių tiekėjų ir   nepatikimųjų tiekėjų sąrašai   ·          Teisminio nagrinėjimo duomenys   ·          Konsolidavimo su kitomis PO duomenys

**Comment by sirex** [comment]
Per mažas paveiksliukas, sunku įskaityti, kas ten parašyta.
