### ISSUE TITLE
3.3.2	Duomenų valdymo schema

### ISSUE THREAD

**Issue by RMasiliunaite** [Viesuju-pirkimu-tarnyba/saule#92]
![image](https://user-images.githubusercontent.com/61745726/81700711-b78e6800-9471-11ea-9e7a-a38b953b62de.png)6 pav. Saulė IS duomenų valdymo schema

Schemoje pateiktas apdorotų ir neapdorotų (angl. Raw data) duomenų pasiskirstymas tarp realizuojamų SAULĖ IS komponentų principinė duomenų valdymo schema ir turi būti detalizuojama ir tikslinama projektavimo etape.

Lentelė 16. Reikalavimai SAULĖ IS duomenų valdymui

Reikalavimas | Nr.
-- | --
Turi būti sukurtas didelių   duomenų platforminis sprendimas ir pateikti visi reikalingi komponentai   užtikrinant neapdorotų duomenų paėmimą/ gavimą iš duomenų šaltinių/išorinio   bei vidinio Saulė IS portalų ar kitų išorinių informacinių sistemų ir   registrų bei tuos duomenis reikiama apimtimi ir reikiamu formatu išsaugoti   HDFS tolimesnei analizei bei apdorojimui. | 1.
Duomenų valdymui turi būti   sukurti atitinkami šio komponento ir kitų išvardintų duomenų šaltinių/ir   duomenis saugojančio HDFS ryšiai/sąsajos.   Gali būti naudojama Sqoop,   Flume, Kafka, Atlas, NFS, WebHDFS ar lygiavertė programinė įranga. Sąsajoms   užtikrinti gali būti naudojamas daugiau nei vienas komponentas. | 2.
Didelių duomenų platformoje   turi būti įdiegta NoSQL tipo duomenų bazė (HBase ar lygiavertė), skirta   didelės apimties struktūrizuotai ir nestruktūrizuotai informacijai saugoti ir   tvarkyti. | 3.
Duomenų analizei ir   paieškoms turi būti pateikta atitinkama    specializuota programinė įranga. Gali būti naudojama MapReduce, Pig,   Solr, Spark, Impala, Hive ar lygiavertė programinė įranga. Duomenų skaitymui   užtikrinti gali būti naudojamas daugiau nei vienas komponentas. | 4.

**Comment by sirex** [comment]
Paveiksliukas visiškai neįskaitomas.
