### ISSUE TITLE
3.4.1	Principinė SAULĖ IS saugos (hibridinės saugos) architektūros schema

### ISSUE THREAD

**Issue by RMasiliunaite** [Viesuju-pirkimu-tarnyba/saule#94]
![image](https://user-images.githubusercontent.com/61745726/81700849-e60c4300-9471-11ea-8707-3f8c121a2675.png)7 pav. Saulė IS principinė saugos (hibridinės saugos) architektūros schema

SAULĖ IS saugos architektūrą galima išskaidyti į tris saugos sluoksnius:
•	Į pirmąjį saugos sluoksnį patenka VPT ir kitų priežiūros ir įgyvendinančių institucijų (ĮI) patalpose esanti infrastruktūra ir joje veikiantys komponentai;
•	Antrasis saugos sluoksnis apima ryšių tinklus ir komunikaciją jais. Saugi komunikacija ryšių tinklais turi būti užtikrinama naudojant VPN, HTTPS ir kitas lygiavertes saugaus ryšio užtikrinimo priemones ir technologijas. Išorinių portalo „SAULĖ“ naudotojų (Visuomenės, Pirkimo vykdytojų, Tiekėjų) prieigai prie portalo „SAULĖ“ turi būti naudojamas HTTPS protokolas, o VPT ir kitų priežiūros ir įgyvendinančių institucijų (ĮI) specialistų prieigai prie SAULĖ IS vidinio portalo ir susijusių komponentų papildomai turi būti naudojami VPN protokolai;
•	Trečiasis saugos sluoksnis apima VDPT infrastuktūroje dislokuotus SAULĖ IS komponentus.

**Comment by aleksejkovaliov** [comment]
Aprašyti tradiciniai tinklo saugos principai. Prašome paaiškinti "hibridinės saugos" terminą ir ypatumus, ar yra numatomos kažkokios papildomos "hibridinės" priemonės, kurios nėra pavaizduotos schemoje?

**Comment by RMasiliunaite** [comment]
> Aprašyti tradiciniai tinklo saugos principai. Prašome paaiškinti "hibridinės saugos" terminą ir ypatumus, ar yra numatomos kažkokios papildomos "hibridinės" priemonės, kurios nėra pavaizduotos schemoje?

Terminas Hibridinė sauga suprantamas kaip SAULĖ IS komponentų, veikiančių paskirstytoje infrastruktūroje (angl. Hybrid Cloud), saugą užtikrinančių organizacinių ir techninių saugos priemonių visuma. Hibridinės saugos priemonės bus taikomos visuose principinę tinklo schemą vaizduojančiuose lygiuose, siekiant, kad SAULĖ IS komponentai ir duomenys būtų apsaugoti ir ginami nuo pažeidimų, neteisėto naudojimo arba pakeitimo, išnaudojimo, klaidingų sprendimo priėmimo.
